"""Capability-owned application control interfaces."""

from __future__ import annotations

from typing import Any, Mapping, Protocol


class AdapterError(RuntimeError):
    """Application command or observation failed."""


class SpotifyAdapter(Protocol):
    async def open(self) -> None: ...
    async def search(self, query: str) -> None: ...
    async def play_result(self, query: str | None) -> None: ...
    async def pause(self) -> None: ...
    async def resume(self) -> None: ...
    async def skip(self) -> None: ...
    async def observe(self) -> Mapping[str, Any]: ...


class BrowserAdapter(Protocol):
    async def open(self) -> None: ...
    async def search(self, query: str) -> None: ...
    async def navigate(self, target: str) -> None: ...
    async def back(self) -> None: ...
    async def forward(self) -> None: ...
    async def observe(self) -> Mapping[str, Any]: ...
